apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: procyon-dashboard-treafik-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: procyon-dashboard-treafik
    k8s.kuboard.cn/workload: procyon-dashboard-treafik
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure, web
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-http-redirect-https@kubernetescrd,
                                                      kube-system-http-redirect-https-testing@kubernetescrd,
                                                      kube-system-common-headers@kubernetescrd

spec:
  tls:
    - hosts:
        - dashboard.procyon.vip
      secretName: procyon-vip-cert
    - hosts:
        - dashboard.npool.top
      secretName: npool-top-cert
  rules:
    - host: dashboard.procyon.vip
      http:
        paths:
          - path: /
            backend:
              serviceName: procyon-dashboard
              servicePort: 80
    - host: dashboard.npool.top
      http:
        paths:
          - path: /
            backend:
              serviceName: procyon-dashboard
              servicePort: 80
